/**
 * Created with IntelliJ IDEA.
 * User: Administrator
 * Date: 5/22/13
 * Time: 12:50 AM
 * To change this template use File | Settings | File Templates.
 */
class DefinitionWriter {
	Config config
	File definitionFile
	File factoryFile
	File configFile

	def init() {
		new File( config.outputPath ).deleteDir()
		new File( config.outputPath ).mkdir()

		//		definitionFile = new File( "${ config.outputPath }/${ config.libraryName }-${ config.libraryVersion }-${ config.useFullTyping ? 'Typed' : 'Untyped' }${ config.interfaceOnly ? '-Interfaces' : '' }.d.ts" )
		//		factoryFile = new File( "${ config.outputPath }/${ config.libraryName }-${ config.libraryVersion }-${ config.useFullTyping ? 'Typed' : 'Untyped' }${ config.interfaceOnly ? '-Interfaces' : '' }-factory.ts" )
		//		configFile = new File( "${ config.outputPath }/${ config.libraryName }-${ config.libraryVersion }-${ config.useFullTyping ? 'Typed' : 'Untyped' }${ config.interfaceOnly ? '-Interfaces' : '' }-config.d.ts" )

		definitionFile = new File( "${ config.outputPath }/ExtJS.d.ts" )
		factoryFile = new File( "${ config.outputPath }/ExtJS-factory.ts" )
		configFile = new File( "${ config.outputPath }/ExtJS-config.d.ts" )

		println "generating file " + definitionFile.absolutePath
		println "generating file " + factoryFile.absolutePath
		println "generating file " + configFile.absolutePath

		if( config.singleDefinition ) {
			definitionFile.write( "" )
			writeToDefinition( "// Type definitions for ${ config.libraryName } ${ config.libraryVersion }" )
			writeToDefinition( "// Forked Project: http://www.sencha.com/products/${ config.libraryName.toLowerCase() }/" )
			writeToDefinition( "// Definitions by: Brian Kotek <https://github.com/brian428/>" )
			writeToDefinition( "// Definitions: https://github.com/borisyankov/DefinitelyTyped\n" )
			writeToDefinition( "" )
			writeToDefinition( "///<reference path='./ExtJS-user.d.ts'/>" )
			writeToDefinition( "" )
			
			writeToFactory( "// Factory for ${ config.libraryName } ${ config.libraryVersion }" )
			writeToFactory( "// Forked Project: http://www.sencha.com/products/${ config.libraryName.toLowerCase() }/" )
			writeToFactory( "// Generated by Jeremie Turbet @IPBS - Toulouse")
			writeToFactory( "" )

			writeToConfig( "// Config for ${ config.libraryName } ${ config.libraryVersion }" )
			writeToConfig( "// Forked Project: http://www.sencha.com/products/${ config.libraryName.toLowerCase() }/" )
			writeToConfig( "// Generated by Jeremie Turbet @IPBS - Toulouse")
			writeToConfig( "")
		}

		if( config.libraryName != "ExtJS" && config.libraryName != "Touch" ) {
			writeToDefinition( "declare module Ext { export interface IBase {} }\n" )
		}
	}

	def writeToFactory( value ) {
		value = value.replaceAll( "(  ){1,100}", " " )
		//		println "Factory writer :\t\t\t\t |  " + value
		factoryFile.withWriterAppend( "UTF-8" ) { writer ->
			writer << value + "\n"
		}
	}

	def writeToConfig( value ) {
		value = value.replaceAll( "(  ){1,100}", " " )
		//		println "Config writer :\t\t\t\t |  " + value
		configFile.withWriterAppend( "UTF-8" ) { writer ->
			writer << value + "\n"
		}
	}

	def writeToDefinition( value ) {
		value = value.replaceAll( "(  ){1,100}", " " )
		if( config.singleDefinition ) {
			definitionFile.withWriterAppend( "UTF-8" ) { writer ->
				writer << value + "\n"
			}
		}
		else {
			def currentDefinitionFile = new File( "${ config.outputPath }/${ config.currentModule }.d.ts" )
			if( !currentDefinitionFile.exists() ) currentDefinitionFile.createNewFile()

			currentDefinitionFile.withWriterAppend( "UTF-8" ) { writer ->
				writer << value + "\n"
			}
		}
	}

	def formatCommentText( comment ) {
		def result = ""
		if( comment ) result += comment.replaceAll("<(.|\n)*?>", "").replaceAll( "[\\n\\t]", " " )
		return result
	}
}
